// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeC4DRYWtS1OgTojYDPhJfep3O0xglsDM',
    appId: '1:130623829878:web:0dd2d1c18e57f4a2b8ec57',
    messagingSenderId: '130623829878',
    projectId: 'login-moyobap-app',
    authDomain: 'login-moyobap-app.firebaseapp.com',
    storageBucket: 'login-moyobap-app.firebasestorage.app',
    measurementId: 'G-KX9EMZR024',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJN5TV6CU9FqnieSZ3Q4zoj9iljiOfqVk',
    appId: '1:130623829878:android:d04ea3cb00825560b8ec57',
    messagingSenderId: '130623829878',
    projectId: 'login-moyobap-app',
    storageBucket: 'login-moyobap-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxV9D-uaq1vOL4HLAOzsCkcD9YZyPGarU',
    appId: '1:130623829878:ios:f23aa289533ce6abb8ec57',
    messagingSenderId: '130623829878',
    projectId: 'login-moyobap-app',
    storageBucket: 'login-moyobap-app.firebasestorage.app',
    iosBundleId: 'com.example.moyobaplogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxV9D-uaq1vOL4HLAOzsCkcD9YZyPGarU',
    appId: '1:130623829878:ios:f23aa289533ce6abb8ec57',
    messagingSenderId: '130623829878',
    projectId: 'login-moyobap-app',
    storageBucket: 'login-moyobap-app.firebasestorage.app',
    iosBundleId: 'com.example.moyobaplogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeC4DRYWtS1OgTojYDPhJfep3O0xglsDM',
    appId: '1:130623829878:web:cd59a4fb8afa9327b8ec57',
    messagingSenderId: '130623829878',
    projectId: 'login-moyobap-app',
    authDomain: 'login-moyobap-app.firebaseapp.com',
    storageBucket: 'login-moyobap-app.firebasestorage.app',
    measurementId: 'G-H7TXJG268B',
  );
}
